#%RAML 1.0 NamedExample
getTopics-example:
  -
    id: 1
    name: Spring boot
    description: description of advanced spring concepts
  - 
    id: 2
    name: Spring Framework
    description: description of containers and xml configuration